title: "点名器"
email: himself6565@gmail.com
description:
  "上课点名器"
url: "http://random.himself65.com"
baseurl: ""

weibo_username:     Himself65
zhihu_username:     Himself65
github_username:    Himself65
twitter_username:   MrSweerBread
